import re
from fpdf import FPDF


def sanitize(text):
    """Remove characters outside latin-1 range (e.g. emojis) so fpdf doesn't crash."""
    if not isinstance(text, str):
        text = str(text)
    # Replace common emoji-adjacent unicode with safe alternatives
    text = text.replace('\u2014', '-').replace('\u2013', '-').replace('\u2019', "'")
    text = text.replace('\u201c', '"').replace('\u201d', '"')
    # Strip anything above latin-1 range
    return text.encode('latin-1', errors='ignore').decode('latin-1')


class PDF(FPDF):
    def __init__(self):
        super().__init__()
        self.set_auto_page_break(auto=True, margin=15)
        self.add_page()

    def header(self):
        self.set_font('Arial', 'B', 18)
        self.set_text_color(80, 40, 160)
        self.cell(0, 12, 'NutriAI - Personalised Meal Plan', ln=True, align='C')
        self.set_text_color(0, 0, 0)
        self.set_draw_color(168, 85, 247)
        self.set_line_width(0.8)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by NutriAI', align='C')

    def user_info(self, user_data):
        self.set_font('Arial', 'B', 13)
        self.set_text_color(60, 60, 60)
        self.cell(0, 8, 'User Profile', ln=True)
        self.set_draw_color(200, 200, 200)
        self.set_line_width(0.3)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(3)

        self.set_font('Arial', '', 11)
        self.set_text_color(40, 40, 40)
        fields = [
            ('Name',     user_data.get('name', 'N/A')),
            ('Age',      f"{user_data.get('age', 'N/A')} years"),
            ('Gender',   user_data.get('gender', 'N/A')),
            ('Diet',     user_data.get('diet', 'N/A')),
            ('BMR',      f"{user_data.get('bmr', 'N/A')} kcal/day"),
            ('BMI',      f"{user_data.get('bmi', 'N/A')} ({user_data.get('bmi_cat', '')})"),
            ('TDEE',     f"{user_data.get('tdee', 'N/A')} kcal/day"),
        ]
        for label, value in fields:
            self.set_font('Arial', 'B', 11)
            self.cell(40, 7, sanitize(f"{label}:"))
            self.set_font('Arial', '', 11)
            self.cell(0, 7, sanitize(str(value)), ln=True)
        self.ln(4)

    def meal_section(self, meal):
        # Section header
        self.set_fill_color(245, 240, 255)
        self.set_font('Arial', 'B', 14)
        self.set_text_color(80, 40, 160)
        title_text = sanitize(f"{meal['title']}  -  {meal['calories']} Calories")
        self.cell(0, 10, title_text, ln=True, fill=True)
        self.set_text_color(40, 40, 40)
        self.ln(2)

        # Items
        self.set_font('Arial', 'B', 11)
        self.cell(0, 7, 'Meal Items:', ln=True)
        self.set_font('Arial', '', 11)
        for item in meal.get('items', []):
            self.cell(0, 6, sanitize(f"  - {item.replace('_', ' ').title()}"), ln=True)
        self.ln(2)

        # Description
        self.set_font('Arial', 'B', 11)
        self.cell(0, 7, 'AI Description:', ln=True)
        self.set_font('Arial', '', 11)
        desc = sanitize(str(meal.get('description', '')))
        self.multi_cell(190, 6, desc)
        self.ln(2)

        # Recipe (dict format)
        recipe = meal.get('recipe', {})
        if recipe:
            self.set_font('Arial', 'B', 11)
            self.cell(0, 7, 'Recipe Details:', ln=True)
            self.set_font('Arial', '', 11)
            for key, val in recipe.items():
                if key == 'Instructions':
                    self.set_font('Arial', 'B', 10)
                    self.cell(0, 6, sanitize(f"{key}:"), ln=True)
                    self.set_font('Arial', '', 10)
                    self.multi_cell(190, 6, sanitize(str(val)))
                else:
                    label = sanitize(f"  {key}: ")
                    value = sanitize(str(val).replace('_', ' ').title() if key != 'Calories' else str(val))
                    self.set_font('Arial', 'B', 10)
                    self.cell(45, 6, label)
                    self.set_font('Arial', '', 10)
                    self.cell(0, 6, value, ln=True)
        self.ln(5)


def create_meal_plan_pdf(meals_data, user_info, filename="meal_plan.pdf"):
    pdf = PDF()
    pdf.user_info(user_info)
    for meal in meals_data:
        pdf.meal_section(meal)
    pdf.output(filename)
